steps:
# === Menu recognizer ===
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/menu-recognizer:latest'
    - '--file=menu-recognizer/Dockerfile'
    - './menu-recognizer'
  id: 'menu-recognizer_build'
# Push to registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/menu-recognizer:latest']
  wait_for: ['menu-recognizer_build']
  id: 'menu-recognizer_push'
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
  - 'run'
  - 'deploy'
  - 'menu-recognizer'
  - '--image'
  - 'gcr.io/$PROJECT_ID/menu-recognizer:latest'
  - '--region'
  - 'us-east1'
  - '--platform'
  - 'managed'
  - '--memory'
  - '450Mi'
  wait_for: ['menu-recognizer_push']
  id: 'menu-recognizer_deploy'

images:
- 'gcr.io/$PROJECT_ID/menu-recognizer:latest'