[tool.poetry]
name = "schema"
version = "0.1.0"
description = ""
authors = ["Amjad Saadeh <mail@amjadsaadeh.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
